<?php
/**
 * @file
 *  A parser to test Sourcery's parser functions
 * @copyright Copyright(c) 2012 Christopher Skene
 * @license GPL v2 http://www.fsf.org/licensing/licenses/gpl.html
 * @author Chris Skene chris at xtfer dot com
 */

$plugin = array(
  'name'        => 'sourcery_test_parser',
  'module'      => 'sourcery_tests',
  'class'       => 'SourceryTestParser',
  'label'       => t('Test Parser'),
  'description' => t('A parser to test Drupal\sourcery\'s Parser functions'),
);

/**
 * A parser to test Sourcery's parser functions
 */
class SourceryTestParser {

  // @todo: do stuff here...
}
